export type QuestionType =
  | "welcome"
  | "shortText"
  | "multipleChoice"
  | "longText"
  | "pictureChoice"
  | "questionGroup"
  | "dropdown"
  | "numerical"
  | "opinionScale"
  | "email"
  | "rating"
  | "linkWeb"
  | "ranking"
  | "statement"
  | "fileUpload"
  | "endings"
  | null;
